version: '3.8'
services:
  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_PID: 'Developer'
      MSSQL_SA_PASSWORD: 'Sqlserver!P4ssw0rd'
      ACCEPT_EULA: 'Y'
    ports:
      - "1433:1433"
    container_name: sql_server
    hostname: sql_server_2019
    restart: always
