$script1 = <<-SCRIPT
sudo apt update -y
sudo apt install docker.io -y
sudo groupadd docker
sudo usermod -aG docker vagrant
newgrp docker
sudo apt install curl -y
SCRIPT

$script2 = <<-SHELL
cat /vagrant/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
SHELL

Vagrant.configure("2") do |config|
    config.vm.box = "aspyatkin/ubuntu-20.04-server"
    #config.vm.usable_port_range = 80..32000
    config.vm.provision "shell", inline: $script1
    #config.vm.synced_folder "app", "/app"
    config.vm.provision "shell", inline: $script2

    config.vm.define "masterNode" do |masterNode|
        masterNode.vm.network "forwarded_port", guest: 80, host: 80
        masterNode.vm.network "forwarded_port", guest: 443, host: 443
        masterNode.vm.hostname = "masterNode"
        masterNode.vm.network "public_network", ip: "192.168.1.50"
        masterNode.vm.provider "virtualbox" do |vb|
            vb.cpus = 2
            vb.memory = 2048
        end
    end

    config.vm.define "workerNode1" do |workerNode1|
        workerNode1.vm.hostname = "workerNode1"
        workerNode1.vm.network "public_network", ip: "192.168.1.51"
        workerNode1.vm.provider "virtualbox" do |vb|
            vb.cpus = 2
            vb.memory = 2048
        end
    end

    config.vm.define "workerNode2" do |workerNode2|
        workerNode2.vm.hostname = "workerNode2"
        workerNode2.vm.network "public_network", ip: "192.168.1.52"
        workerNode2.vm.provider "virtualbox" do |vb|
            vb.cpus = 2
            vb.memory = 2048
        end
    end

end